# Generated by Django 3.1.2 on 2020-11-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calls',
            name='FollowupDate',
        ),
        migrations.AlterField(
            model_name='calls',
            name='Followup',
            field=models.IntegerField(blank=True, choices=[(180, '6اشهر'), (365, 'سنه'), (730, 'سنتين')], null=True),
        ),
        migrations.AlterField(
            model_name='calls',
            name='Note',
            field=models.TextField(max_length=100),
        ),
    ]
