# Generated by Django 3.1.2 on 2020-11-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_auto_20201124_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='FollowupIN',
            field=models.DateField(blank=True, null=True),
        ),
    ]
