# Generated by Django 3.1.2 on 2020-11-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_calls_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calls',
            name='Followup',
            field=models.IntegerField(blank=True, choices=[(1, '1 day'), (2, '2days'), (3, '3days'), (4, '4days'), (5, '5days'), (6, '6days'), (7, 'week'), (14, 'weeks'), (30, 'Month')], null=True),
        ),
    ]
