# Generated by Django 3.1.2 on 2020-11-22 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='even_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='events',
            name='event_type',
        ),
    ]
