# Generated by Django 3.1.2 on 2020-11-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage', '0002_auto_20201122_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='id',
            new_name='even_id',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='start',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='events',
            name='event_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
