# Generated by Django 3.1.2 on 2020-11-22 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage', '0003_auto_20201122_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='even_id',
            new_name='event_id',
        ),
    ]
