# Generated by Django 3.1.2 on 2020-11-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage', '0005_cruduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='allDay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='backgroundColor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='borderColor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
