# Generated by Django 3.1.2 on 2020-11-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage', '0006_auto_20201122_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='arrive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='arrivetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
