# Generated by Django 3.1.2 on 2020-12-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0026_auto_20201201_2124'),
        ('event_manage', '0009_auto_20201130_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.patient'),
        ),
    ]
