# Generated by Django 3.1.2 on 2020-12-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage', '0011_events_session_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='start',
            field=models.BooleanField(default=False),
        ),
    ]
