# Generated by Django 3.1.2 on 2020-12-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_manage', '0012_events_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end',
            field=models.BooleanField(default=False),
        ),
    ]
