# Generated by Django 3.1.2 on 2020-11-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description_long',
        ),
        migrations.RemoveField(
            model_name='item',
            name='stock_no',
        ),
        migrations.AddField(
            model_name='item',
            name='CountBalces',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='PackageParts',
            field=models.ManyToManyField(blank=True, null=True, related_name='itemPackageParts', to='novav1.pricing'),
        ),
    ]
