# Generated by Django 3.1.2 on 2020-11-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0003_auto_20201113_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='BalcesNumber',
            field=models.FloatField(default=0),
        ),
    ]
