# Generated by Django 3.1.2 on 2020-11-13 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0005_auto_20201113_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.patient'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='Patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novav1.patient'),
        ),
    ]
