# Generated by Django 3.1.2 on 2020-11-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0006_auto_20201113_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='AmountBalance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='BallceBalance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='RemmainingBalance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='Remmainingamount',
            field=models.IntegerField(default=0),
        ),
    ]
