# Generated by Django 3.1.2 on 2020-11-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0007_auto_20201117_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='PatientName',
            field=models.CharField(blank=True, db_column='FirstName', max_length=50, null=True, unique=True),
        ),
    ]
