# Generated by Django 3.1.2 on 2020-11-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0009_auto_20201118_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='paid',
            field=models.IntegerField(default=0),
        ),
    ]
