# Generated by Django 3.1.2 on 2020-11-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0011_auto_20201118_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
