# Generated by Django 3.1.2 on 2020-11-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0013_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.AddField(
            model_name='order',
            name='Cash',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='Discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='Net',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='Remmaining',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='TotalPrice',
            field=models.FloatField(default=0),
        ),
    ]
