# Generated by Django 3.1.2 on 2020-11-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0014_auto_20201119_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Net',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='Remmaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='TotalPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='novav1.OrderItem'),
        ),
    ]
