# Generated by Django 3.1.2 on 2020-11-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0016_order_balls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
