# Generated by Django 3.1.2 on 2020-11-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0017_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(blank=True, choices=[(1, 'SALE'), (2, 'BALLS TRANSFER'), (3, 'PYMENT')], default=1, null=True),
        ),
    ]
