# Generated by Django 3.1.2 on 2020-11-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0018_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Refunds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='ballsRemmaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(blank=True, choices=[(1, 'SALE'), (2, 'BALLS TRANSFER'), (3, 'PYMENT'), (4, 'Refunds')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
