# Generated by Django 3.1.2 on 2020-11-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0019_auto_20201127_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Patient_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Patient_from', to='novav1.patient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(blank=True, choices=[(1, 'SALE'), (2, 'BALLS TRANSFER Add '), (3, 'BALLS TRANSFER reducing '), (4, 'PYMENT'), (5, 'Refunds')], default=1, null=True),
        ),
    ]
