# Generated by Django 3.1.2 on 2020-11-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0020_auto_20201127_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='received',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_requested',
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='A7AYPDVLCM7821ZD79XK', max_length=20),
        ),
        migrations.CreateModel(
            name='ballses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.IntegerField()),
                ('ballses_count', models.IntegerField()),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novav1.patient')),
            ],
        ),
    ]
