# Generated by Django 3.1.2 on 2020-11-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0021_auto_20201127_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('Cash_efect', models.IntegerField(default=0)),
                ('Balls_efect', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='P4MVD4T3Z7VZ1TACSQHL', max_length=20),
        ),
    ]
