# Generated by Django 3.1.2 on 2020-11-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0022_auto_20201129_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='55U9LFGKK31T5BGOHNNP', max_length=20),
        ),
    ]
