# Generated by Django 3.1.2 on 2020-11-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0024_auto_20201130_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='TGHN5C1IV0A1W8GR6HH2', max_length=20),
        ),
    ]
