# Generated by Django 3.1.2 on 2020-12-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0025_auto_20201130_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='6WNXQE14SNTVEJJCYVJI', max_length=20),
        ),
    ]
