# Generated by Django 3.1.2 on 2020-12-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0026_auto_20201201_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='LZKYEPXO1PZHXFBFG39X', max_length=20),
        ),
    ]
