# Generated by Django 3.1.2 on 2020-12-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0027_auto_20201202_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='D2474UF22ARSROATY3FY', max_length=20),
        ),
    ]
