# Generated by Django 3.1.2 on 2020-12-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0029_auto_20201202_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='3DCAFOTV8A1ZJF9RP05I', max_length=20),
        ),
    ]
