# Generated by Django 3.1.2 on 2020-12-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novav1', '0031_auto_20201202_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Net',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='TGU9G9L2HG9T3VWDOZXC', max_length=20),
        ),
    ]
